# Generated by Django 2.0.7 on 2019-04-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Security_ID',
            field=models.CharField(default='xxx-xxx-xxx', max_length=50),
        ),
    ]
