# Generated by Django 2.0.7 on 2019-06-04 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_customuser_security_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Security_ID',
            new_name='license',
        ),
    ]
