# Generated by Django 2.0.7 on 2019-06-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20190604_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(default='profile/users.png', upload_to='profile'),
        ),
    ]
