# Generated by Django 2.0.7 on 2019-06-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_customuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='lagos', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='08000012345', max_length=150),
        ),
    ]
