# Generated by Django 2.0.7 on 2019-04-29 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_cart_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
    ]
