# Generated by Django 2.0.7 on 2019-05-06 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pickup_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
