# Generated by Django 2.0.7 on 2019-05-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_auto_20190506_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='automobile',
            field=models.ManyToManyField(blank=True, to='Transport.Rent'),
        ),
    ]
