# Generated by Django 2.0.7 on 2019-05-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_auto_20190514_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='automobile',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='return_date',
        ),
    ]
