# Generated by Django 2.0.7 on 2019-05-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_auto_20190506_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_date',
        ),
    ]
