# Generated by Django 2.0.7 on 2019-04-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Vehicle_id',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='Brands',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='Vehicle_id',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Brands',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Vehicle_id',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='Brands',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='Vehicle_id',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
