# Generated by Django 2.0.7 on 2019-04-29 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0006_auto_20190429_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='Brands',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Transport.Brand'),
        ),
    ]
