# Generated by Django 2.0.7 on 2019-04-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0007_automobile_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='image',
            field=models.ImageField(blank=True, default='Users/Model/user.png', upload_to='Users/Model'),
        ),
    ]
