# Generated by Django 2.0.7 on 2019-05-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0008_automobile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='image',
            field=models.ImageField(blank=True, default='Users/Model/user.png', upload_to='AutoMobile'),
        ),
    ]
