# Generated by Django 2.0.7 on 2019-05-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0010_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='total',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='update',
        ),
    ]
