# Generated by Django 2.0.7 on 2019-05-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0011_auto_20190514_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='automobile',
            new_name='Automobile',
        ),
    ]
