# Generated by Django 2.0.7 on 2019-05-14 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_auto_20190514_1627'),
        ('Transport', '0012_auto_20190514_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='Cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cart.cart'),
        ),
    ]
