# Generated by Django 2.0.7 on 2019-05-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0014_auto_20190514_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='Cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
