# Generated by Django 2.0.7 on 2019-05-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0015_rent_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
