# Generated by Django 2.0.7 on 2019-05-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0016_rent_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='driver',
            field=models.BooleanField(default=False),
        ),
    ]
