# Generated by Django 2.0.7 on 2019-05-19 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0017_rent_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='Automobile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Transport.AutoMobile'),
        ),
    ]
