# Generated by Django 2.0.7 on 2019-06-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0018_auto_20190519_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
