# Generated by Django 2.0.7 on 2019-06-04 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0019_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='driver',
        ),
    ]
